name: run_main
on: [push]
jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python main.py
      - run: git config --global user.email "readme-bot@example.com"
      - run: git config --global user.name "README-bot"
      - run: git add .
      - run: git commit -m "update README.md"
      - run: git push

