name: run_main
on: [push]
jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python main.py
      - run: git add .
      - run: git commit -m "add file"
