name: run_main
on: [push]
jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python main.py
      - run: git add .
      - run: git config user.email "richard.a.cairns@gmail.com"
      - run: git config user.name "Rich"

      - run: git commit -m "add file"
